//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpRegexTool {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyntaxRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyntaxRes() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpRegexTool.SyntaxRes", typeof(SyntaxRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Windows;
        ///
        ///public class Script
        ///{
        ///    public string Replace(Match match, int index, string fileName, int globalIndex, int fileIndex)
        ///    {
        ///        //code
        ///        // return string.Empty;
        ///    }
        ///
        ///    public string Replace(Match match, Group group, int index, string fileName, int globalIndex, int fileIndex)
        ///    {
        ///        //code
        ///        // return string.Empty [stringa troncata]&quot;;.
        /// </summary>
        internal static string CSharpReplaceContainer {
            get {
                return ResourceManager.GetString("CSharpReplaceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;Regex&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///    &lt;Color name=&quot;CharClass&quot; foreground=&quot;Blue&quot; fontWeight=&quot;bold&quot;/&gt;
        ///    &lt;Color name=&quot;NegativeCharClass&quot; foreground=&quot;OrangeRed&quot; fontWeight=&quot;bold&quot;/&gt;
        ///    &lt;Color name=&quot;Quantifier&quot; foreground=&quot;DarkViolet&quot; fontWeight=&quot;bold&quot;/&gt;
        ///    &lt;Color name=&quot;QuantifierNumber&quot; foreground=&quot;Red&quot; fontWeight=&quot;normal&quot;/&gt;
        ///    &lt;Color name=&quot;CharEscape&quot; foreground=&quot;Gray&quot; fontWeight=&quot;normal&quot;/&gt;
        ///    &lt;Color name=&quot;Comment [stringa troncata]&quot;;.
        /// </summary>
        internal static string Regex_syntax_color {
            get {
                return ResourceManager.GetString("Regex_syntax_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///    &quot;Data&quot;: [
        ///        {
        ///            &quot;Name&quot;: &quot;Character Escapes&quot;,
        ///            &quot;Description&quot;: &quot;Escape characters that signal to the regular expression parser a special char&quot;,
        ///            &quot;Elements&quot;: [
        ///                {
        ///                    &quot;Name&quot;: &quot;Bell &quot;,
        ///                    &quot;Description&quot;: &quot;Matches a bell (alarm) \\u0007.&quot;,
        ///                    &quot;Value&quot;: &quot;\\a&quot;
        ///                },
        ///                {
        ///                    &quot;Name&quot;: &quot;Backspace &quot;,
        ///                    &quot;Description&quot;: &quot;Matches a backspace \\u [stringa troncata]&quot;;.
        /// </summary>
        internal static string RegexLanguageElements {
            get {
                return ResourceManager.GetString("RegexLanguageElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;Regex&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///    &lt;Color name=&quot;Substitution&quot; foreground=&quot;Blue&quot; fontWeight=&quot;bold&quot;/&gt;
        ///
        ///    &lt;RuleSet&gt;
        ///        &lt;Rule color=&quot;Substitution&quot;&gt;
        ///            \$([$`&apos;+_&amp;amp;]|\d+(?!\d)|([{]\w*[}]))
        ///        &lt;/Rule&gt;
        ///    &lt;/RuleSet&gt;
        ///&lt;/SyntaxDefinition&gt;.
        /// </summary>
        internal static string Replace_syntax_color {
            get {
                return ResourceManager.GetString("Replace_syntax_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///    &quot;Data&quot;: [
        ///        {
        ///            &quot;Name&quot;: &quot;Value of matched group by group number &quot;,
        ///            &quot;Description&quot;: &quot;Substitutes the last substring matched by group number (decimal).&quot;,
        ///            &quot;Value&quot;: &quot;$number&quot;
        ///        },
        ///        {
        ///            &quot;Name&quot;: &quot;Value of matched group by group name &quot;,
        ///            &quot;Description&quot;: &quot;Substitutes the last substring matched by group name (string).&quot;,
        ///            &quot;Value&quot;:&quot;${name}&quot;
        ///        },
        ///        {
        ///            &quot;Name&quot;: &quot;Dollar sign &quot;,
        ///            &quot;Descrip [stringa troncata]&quot;;.
        /// </summary>
        internal static string ReplaceLanguageElements {
            get {
                return ResourceManager.GetString("ReplaceLanguageElements", resourceCulture);
            }
        }
    }
}
